# render.yaml
# Configuration pour déploiement sur Render.com
# Documentation: https://render.com/docs/yaml-spec

databases:
  - name: matching-interim-db
    plan: starter # 7$/mois - ou "free" pour PostgreSQL gratuit avec limitations
    databaseName: matching_interim
    user: matching_user
    # Version PostgreSQL
    postgresMajorVersion: 15

services:
  # Service API Backend
  - type: web
    name: matching-interim-api
    runtime: python
    plan: free # Plan gratuit suffisant pour démarrer
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: |
      gunicorn app.main:app \
        --workers 2 \
        --worker-class uvicorn.workers.UvicornWorker \
        --bind 0.0.0.0:$PORT \
        --access-logfile - \
        --error-logfile - \
        --log-level info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: matching-interim-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://matching-interim.onrender.com
      - key: USE_OPENAI
        value: false
      - key: OPENAI_API_KEY
        value: # À remplir si USE_OPENAI=true
      - key: CORS_ORIGINS
        value: '["https://matching-interim.onrender.com", "https://app.matching-interim.com"]'
      - key: DEBUG
        value: false
      - key: MAX_UPLOAD_SIZE
        value: 10485760 # 10MB
    healthCheckPath: /health
    autoDeploy: true # Auto-deploy sur push GitHub

  # Service Frontend Statique
  - type: static
    name: matching-interim-web
    buildCommand: echo "No build needed for static files"
    staticPublishPath: ./frontend
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable